/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipelineImpl.hpp"
#include <PassThroughImplFactory.hpp>
#include "PassThroughImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_pass_through_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoPassThroughImpl"

#define FACTORY_NAME "passthrough"

namespace kurento
{

PassThroughImpl::PassThroughImpl (const boost::property_tree::ptree &config,
                                  std::shared_ptr<MediaPipeline> mediaPipeline)  : MediaElementImpl (config,
                                        std::dynamic_pointer_cast<MediaObjectImpl> (mediaPipeline), FACTORY_NAME)
{
}

MediaObjectImpl *
PassThroughImplFactory::createObject (const boost::property_tree::ptree &config,
                                      std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new PassThroughImpl (config, mediaPipeline);
}

PassThroughImpl::StaticConstructor PassThroughImpl::staticConstructor;

PassThroughImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* kurento */
