/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "ServerInfo.hpp"
#include "MediaPipelineImpl.hpp"
#include "ServerImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_server_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoServerImpl"

namespace kurento
{

ServerImpl::ServerImpl (const boost::property_tree::ptree &config) : MediaObjectImpl (config)
{
  // FIXME: Implement this
}

std::shared_ptr<ServerInfo> ServerImpl::getInfo ()
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "ServerImpl::getinfo: Not implemented");
}

std::vector<std::shared_ptr<MediaPipeline>> ServerImpl::getPipelines ()
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "ServerImpl::getpipelines: Not implemented");
}

std::vector<std::string> ServerImpl::getSessions ()
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "ServerImpl::getsessions: Not implemented");
}

ServerImpl::StaticConstructor ServerImpl::staticConstructor;

ServerImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* kurento */
