/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "ServerInfo.hpp"
#include "MediaPipelineImpl.hpp"
#include "ServerImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include <MediaSet.hpp>

#define GST_CAT_DEFAULT kurento_server_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoServerImpl"

namespace kurento
{

ServerImpl::ServerImpl (const std::shared_ptr<ServerInfo> info,
                        const boost::property_tree::ptree &config) : MediaObjectImpl (config),
  info (info)
{
}

std::shared_ptr<ServerInfo> ServerImpl::getInfo ()
{
  return info;
}

std::vector<std::shared_ptr<MediaPipeline> > ServerImpl::getPipelines()
{
  std::vector<std::shared_ptr<MediaPipeline>> ret;

  for (auto it : MediaSet::getMediaSet ()->getPipelines() ) {
    ret.push_back (std::dynamic_pointer_cast <MediaPipeline> (it) );
  }

  return ret;
}

std::vector<std::string> ServerImpl::getSessions ()
{
  return MediaSet::getMediaSet ()->getSessions();
}

ServerImpl::StaticConstructor ServerImpl::staticConstructor;

ServerImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* kurento */
