/* Autogenerated with kurento-module-creator */

#ifndef __SERVER_IMPL_HPP__
#define __SERVER_IMPL_HPP__

#include "MediaObjectImpl.hpp"
#include "Server.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
class ServerImpl;
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::ServerImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class ServerInfo;
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{

class ServerImpl : public MediaObjectImpl, public virtual Server
{

public:

  ServerImpl (const boost::property_tree::ptree &config);

  virtual ~ServerImpl () {};

  virtual std::shared_ptr<ServerInfo> getInfo ();

  virtual std::vector<std::shared_ptr<MediaPipeline>> getPipelines ();

  virtual std::vector<std::string> getSessions ();

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);

  sigc::signal<void, ObjectCreated> signalObjectCreated;
  sigc::signal<void, ObjectDestroyed> signalObjectDestroyed;
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* kurento */

#endif /*  __SERVER_IMPL_HPP__ */
