${event.name}.cpp
/* Autogenerated with Kurento Idl */

#include "${event.name}.hpp"
#include <jsonrpc/JsonSerializer.hpp>
<#list event.properties as property>
<#if model.remoteClasses?seq_contains(property.type.type) ||
  model.complexTypes?seq_contains(property.type.type) ||
  model.events?seq_contains(property.type.type)>
#include "${property.type.name}.hpp"
</#if>
</#list>

namespace kurento {

void
Serialize(kurento::${event.name}& event, JsonSerializer& s)
{
<#list event.properties as property>
  s.Serialize("${property.name}", event.${property.name});
</#list>
<#if event.extends??>
  try {
    kurento::${event.extends.name} &parent = dynamic_cast<kurento::${event.extends.name}&> (event);

    Serialize(parent, s);
  } catch (std::bad_cast) {

  }
</#if>
}

} /* kurento */
