#ifndef __KMS_HTTP_END_POINT_METHOD_H__
#define __KMS_HTTP_END_POINT_METHOD_H__

G_BEGIN_DECLS

typedef enum
{
  KMS_HTTP_END_POINT_METHOD_GET,
  KMS_HTTP_END_POINT_METHOD_POST,
  KMS_HTTP_END_POINT_METHOD_UNDEFINED
} KmsHttpEndPointMethod;

G_END_DECLS
#endif /* __KMS_HTTP_END_POINT_METHOD_H__ */