#ifndef __KMS_URI_END_POINT_STATE_H__
#define __KMS_URI_END_POINT_STATE_H__

G_BEGIN_DECLS

typedef enum
{
  KMS_URI_END_POINT_STATE_STOP,
  KMS_URI_END_POINT_STATE_START,
  KMS_URI_END_POINT_STATE_PAUSE
} KmsUriEndPointState;

G_END_DECLS
#endif /* __KMS_URI_END_POINT_STATE__ */
