${model.name}Dependencies.cmake
# Autogenerated with ktool-rom-processor
cmake_minimum_required(VERSION 2.8)

find_package(PkgConfig)

###############################################################
# Dependencies
###############################################################
pkg_check_modules(GSTREAMER REQUIRED gstreamer-1.0>=1.3.3)
pkg_check_modules(JSONRPC REQUIRED libjsonrpc>=0.0.6)
pkg_check_modules(SIGCPP REQUIRED sigc++-2.0>=2.0.10)
pkg_check_modules(GLIBMM REQUIRED glibmm-2.4>=2.37)
<#list model.imports as import>
# Todo look for ${import.name} dependencies
</#list>
